import type { RoleDefinition, ToolDefinition } from "./types";
import {
  Base64Tool,
  ColorTool,
  HttpTool,
  ImageInfoTool,
  JsonTool,
  JwtTool,
  MarkdownTool,
  MockDataTool,
  PaletteTool,
  QrTool,
  RegexTool,
  TextTool,
  TimestampTool,
  UrlTool,
  UuidTool,
} from "./tool-panels";

export const roleFilters: RoleDefinition[] = [
  { id: "all", title: "全部工具", hint: "所有岗位" },
  { id: "frontend", title: "前端开发", hint: "颜色、JSON、编码" },
  { id: "backend", title: "后端开发", hint: "请求、令牌、随机值" },
  { id: "qa", title: "测试 / QA", hint: "正则、Mock 数据" },
  { id: "product", title: "产品", hint: "文本、预览、二维码" },
  { id: "design", title: "设计", hint: "取色、图片、配色" },
  { id: "operations", title: "运营", hint: "文案、链接、二维码" },
  { id: "office", title: "办公通用", hint: "文本和格式处理" },
];

export const tools: ToolDefinition[] = [
  {
    id: "http",
    title: "HTTP 请求",
    description: "轻量 Postman，支持 headers、body 和响应查看。",
    roles: ["backend", "frontend", "qa"],
    category: "request",
    keywords: ["postman", "api", "接口", "请求", "headers"],
    component: HttpTool,
  },
  {
    id: "color",
    title: "颜色工具",
    description: "HEX、RGB、HSL 互转，支持图片取色。",
    roles: ["frontend", "design"],
    category: "design",
    keywords: ["取色器", "hex", "rgb", "hsl", "css"],
    component: ColorTool,
  },
  {
    id: "json",
    title: "JSON 工具",
    description: "格式化、压缩、校验 JSON。",
    roles: ["frontend", "backend", "qa"],
    category: "data",
    keywords: ["format", "pretty", "json", "压缩", "校验"],
    component: JsonTool,
  },
  {
    id: "base64",
    title: "Base64",
    description: "文本 Base64 编码与解码。",
    roles: ["frontend", "backend"],
    category: "encoding",
    keywords: ["encode", "decode", "编码", "解码"],
    component: Base64Tool,
  },
  {
    id: "url",
    title: "URL 工具",
    description: "URL 编解码与 Query 参数解析。",
    roles: ["frontend", "backend", "operations", "product"],
    category: "encoding",
    keywords: ["urlencode", "query", "链接", "参数"],
    component: UrlTool,
  },
  {
    id: "timestamp",
    title: "时间戳",
    description: "Unix 时间戳与本地时间互转。",
    roles: ["frontend", "backend", "qa", "office"],
    category: "developer",
    keywords: ["unix", "date", "time", "时间"],
    component: TimestampTool,
  },
  {
    id: "uuid",
    title: "UUID / 随机字符串",
    description: "生成 UUID、Token 和随机密码。",
    roles: ["backend", "qa", "frontend"],
    category: "developer",
    keywords: ["uuid", "random", "token", "密码"],
    component: UuidTool,
  },
  {
    id: "jwt",
    title: "JWT 解码",
    description: "本地解码 Header、Payload 和过期时间。",
    roles: ["backend", "frontend", "qa"],
    category: "developer",
    keywords: ["jwt", "token", "decode", "令牌"],
    component: JwtTool,
  },
  {
    id: "regex",
    title: "正则测试",
    description: "测试正则表达式并高亮匹配结果。",
    roles: ["qa", "frontend", "backend"],
    category: "testing",
    keywords: ["regexp", "match", "匹配", "测试"],
    component: RegexTool,
  },
  {
    id: "mock",
    title: "Mock 数据",
    description: "生成测试姓名、邮箱、地址、日期等。",
    roles: ["qa", "product", "backend"],
    category: "testing",
    keywords: ["mock", "faker", "测试数据", "样例"],
    component: MockDataTool,
  },
  {
    id: "markdown",
    title: "Markdown 预览",
    description: "本地 Markdown 实时预览。",
    roles: ["product", "operations", "office"],
    category: "writing",
    keywords: ["md", "preview", "文档", "预览"],
    component: MarkdownTool,
  },
  {
    id: "text",
    title: "文本处理",
    description: "去重、排序、大小写转换和统计。",
    roles: ["product", "operations", "office", "qa"],
    category: "writing",
    keywords: ["去重", "排序", "大小写", "统计"],
    component: TextTool,
  },
  {
    id: "qr",
    title: "二维码",
    description: "生成可复制的离线二维码草图。",
    roles: ["product", "operations", "office"],
    category: "writing",
    keywords: ["qr", "二维码", "链接", "分享"],
    component: QrTool,
  },
  {
    id: "image-info",
    title: "图片信息",
    description: "查看图片尺寸、格式和文件大小。",
    roles: ["design", "frontend", "operations"],
    category: "design",
    keywords: ["image", "图片", "尺寸", "大小"],
    component: ImageInfoTool,
  },
  {
    id: "palette",
    title: "配色板",
    description: "从主色生成可复制配色。",
    roles: ["design", "frontend", "product"],
    category: "design",
    keywords: ["palette", "配色", "主题色", "颜色"],
    component: PaletteTool,
  },
];
