import type { RoleDefinition, ToolDefinition } from "./types";
import {
  Base64Tool,
  ColorTool,
  ContrastTool,
  CronTool,
  CsvJsonTool,
  DiffTool,
  HashTool,
  HttpTool,
  ImageInfoTool,
  JsonTool,
  JwtTool,
  MarkdownTool,
  MockDataTool,
  PaletteTool,
  QrTool,
  RegexTool,
  TextTool,
  TimestampTool,
  LoremTool,
  UnitTool,
  UrlTool,
  UuidTool,
} from "./tool-panels";
import {
  CalculatorTool,
  CaseTool,
  HtmlEntityTool,
  MortgageTool,
  PasswordTool,
  TimezoneTool,
  XmlTool,
} from "./general-tools";
import { AwsSigV4Tool, HmacTool } from "./advanced-tools";

export const roleFilters: RoleDefinition[] = [
  { id: "all", title: "全部工具", hint: "所有岗位" },
  { id: "frontend", title: "前端开发", hint: "颜色、JSON、编码" },
  { id: "backend", title: "后端开发", hint: "请求、令牌、随机值" },
  { id: "qa", title: "测试 / QA", hint: "正则、Mock 数据" },
  { id: "product", title: "产品", hint: "文本、预览、二维码" },
  { id: "design", title: "设计", hint: "取色、图片、配色" },
  { id: "operations", title: "运营", hint: "文案、链接、二维码" },
  { id: "office", title: "办公通用", hint: "文本和格式处理" },
];

export const tools: ToolDefinition[] = [
  {
    id: "http",
    title: "HTTP 请求",
    description: "轻量 Postman，支持 headers、body 和响应查看。",
    roles: ["backend", "frontend", "qa"],
    category: "request",
    keywords: ["postman", "api", "接口", "请求", "headers"],
    component: HttpTool,
  },
  {
    id: "color",
    title: "颜色工具",
    description: "HEX、RGB、HSL 互转，支持图片取色。",
    roles: ["frontend", "design"],
    category: "design",
    keywords: ["取色器", "hex", "rgb", "hsl", "css"],
    component: ColorTool,
  },
  {
    id: "json",
    title: "JSON 工具",
    description: "格式化、压缩、校验 JSON。",
    roles: ["frontend", "backend", "qa"],
    category: "data",
    keywords: ["format", "pretty", "json", "压缩", "校验"],
    component: JsonTool,
  },
  {
    id: "base64",
    title: "Base64",
    description: "文本 Base64 编码与解码。",
    roles: ["frontend", "backend"],
    category: "encoding",
    keywords: ["encode", "decode", "编码", "解码"],
    component: Base64Tool,
  },
  {
    id: "hash",
    title: "哈希摘要",
    description: "生成 SHA-1、SHA-256、SHA-384、SHA-512 摘要。",
    roles: ["backend", "frontend", "qa"],
    category: "developer",
    keywords: ["hash", "sha", "摘要", "校验", "签名"],
    component: HashTool,
  },
  {
    id: "url",
    title: "URL 工具",
    description: "URL 编解码与 Query 参数解析。",
    roles: ["frontend", "backend", "operations", "product"],
    category: "encoding",
    keywords: ["urlencode", "query", "链接", "参数"],
    component: UrlTool,
  },
  {
    id: "csv-json",
    title: "CSV / JSON",
    description: "表格数据和 JSON 数组互转。",
    roles: ["operations", "product", "qa", "backend"],
    category: "data",
    keywords: ["csv", "excel", "json", "表格", "转换"],
    component: CsvJsonTool,
  },
  {
    id: "timestamp",
    title: "时间戳",
    description: "Unix 时间戳与本地时间互转。",
    roles: ["frontend", "backend", "qa", "office"],
    category: "developer",
    keywords: ["unix", "date", "time", "时间"],
    component: TimestampTool,
  },
  {
    id: "uuid",
    title: "UUID / 随机字符串",
    description: "生成 UUID、Token 和随机密码。",
    roles: ["backend", "qa", "frontend"],
    category: "developer",
    keywords: ["uuid", "random", "token", "密码"],
    component: UuidTool,
  },
  {
    id: "calculator",
    title: "计算器",
    description: "快速计算四则运算、括号和幂运算。",
    roles: ["frontend", "backend", "qa", "office"],
    category: "developer",
    keywords: ["math", "calc", "算式", "计算"],
    component: CalculatorTool,
  },
  {
    id: "password",
    title: "密码生成器",
    description: "生成随机高强度密码并估算强度。",
    roles: ["frontend", "backend", "qa", "office"],
    category: "developer",
    keywords: ["password", "password generator", "随机密码", "口令"],
    component: PasswordTool,
  },
  {
    id: "mortgage",
    title: "房贷计算器",
    description: "计算单笔、组合贷款、提前还款与分步提前还款后的月供和总利息，支持自由增减步骤与自定义缩短年限。",
    roles: ["office", "product", "backend"],
    category: "developer",
    keywords: ["mortgage", "loan", "房贷", "月供", "利息"],
    component: MortgageTool,
  },
  {
    id: "hmac",
    title: "HMAC / Webhook 签名",
    description: "生成并验签 HMAC，适合 Webhook 调试。",
    roles: ["backend", "frontend", "qa"],
    category: "request",
    keywords: ["hmac", "webhook", "signature", "签名", "验签"],
    component: HmacTool,
  },
  {
    id: "sigv4",
    title: "AWS SigV4 签名",
    description: "生成 AWS V4 canonical request 和 Authorization 头。",
    roles: ["backend", "qa", "frontend"],
    category: "request",
    keywords: ["aws", "sigv4", "signature", "canonical request", "签名"],
    component: AwsSigV4Tool,
  },
  {
    id: "html-entity",
    title: "HTML 实体转换",
    description: "HTML 文本与实体编码互转。",
    roles: ["frontend", "backend", "product", "office"],
    category: "writing",
    keywords: ["html", "entity", "escape", "unescape", "实体"],
    component: HtmlEntityTool,
  },
  {
    id: "xml",
    title: "XML 格式化",
    description: "校验 XML 并输出缩进后的结构。",
    roles: ["frontend", "backend", "qa", "operations"],
    category: "data",
    keywords: ["xml", "formatter", "validate", "格式化"],
    component: XmlTool,
  },
  {
    id: "case",
    title: "大小写 / Slug 转换",
    description: "Camel、Snake、Kebab、Title 和 Slug 互转。",
    roles: ["frontend", "backend", "product", "office", "design"],
    category: "writing",
    keywords: ["case", "camel", "snake", "kebab", "slug"],
    component: CaseTool,
  },
  {
    id: "timezone",
    title: "时区转换",
    description: "将本地日期时间转换为常见时区输出。",
    roles: ["frontend", "backend", "qa", "office"],
    category: "developer",
    keywords: ["timezone", "time zone", "date", "datetime", "时区"],
    component: TimezoneTool,
  },
  {
    id: "jwt",
    title: "JWT 解码",
    description: "本地解码 Header、Payload 和过期时间。",
    roles: ["backend", "frontend", "qa"],
    category: "developer",
    keywords: ["jwt", "token", "decode", "令牌"],
    component: JwtTool,
  },
  {
    id: "cron",
    title: "Cron 表达式",
    description: "解释常见 5 段 Cron 定时规则。",
    roles: ["backend", "qa", "operations"],
    category: "developer",
    keywords: ["cron", "定时", "schedule", "任务"],
    component: CronTool,
  },
  {
    id: "regex",
    title: "正则测试",
    description: "测试正则表达式并高亮匹配结果。",
    roles: ["qa", "frontend", "backend"],
    category: "testing",
    keywords: ["regexp", "match", "匹配", "测试"],
    component: RegexTool,
  },
  {
    id: "diff",
    title: "文本 Diff",
    description: "按行比较两段文本差异。",
    roles: ["qa", "product", "office", "frontend", "backend"],
    category: "testing",
    keywords: ["diff", "compare", "对比", "差异", "文案"],
    component: DiffTool,
  },
  {
    id: "mock",
    title: "Mock 数据",
    description: "生成测试姓名、邮箱、地址、日期等。",
    roles: ["qa", "product", "backend"],
    category: "testing",
    keywords: ["mock", "faker", "测试数据", "样例"],
    component: MockDataTool,
  },
  {
    id: "markdown",
    title: "Markdown 预览",
    description: "本地 Markdown 实时预览。",
    roles: ["product", "operations", "office"],
    category: "writing",
    keywords: ["md", "preview", "文档", "预览"],
    component: MarkdownTool,
  },
  {
    id: "text",
    title: "文本处理",
    description: "去重、排序、大小写转换和统计。",
    roles: ["product", "operations", "office", "qa"],
    category: "writing",
    keywords: ["去重", "排序", "大小写", "统计"],
    component: TextTool,
  },
  {
    id: "lorem",
    title: "占位文案",
    description: "生成产品、办公和设计语气的占位文本。",
    roles: ["product", "operations", "design", "office"],
    category: "writing",
    keywords: ["lorem", "占位", "文案", "placeholder", "产品文案"],
    component: LoremTool,
  },
  {
    id: "qr",
    title: "二维码",
    description: "生成可复制的离线二维码草图。",
    roles: ["product", "operations", "office"],
    category: "writing",
    keywords: ["qr", "二维码", "链接", "分享"],
    component: QrTool,
  },
  {
    id: "image-info",
    title: "图片信息",
    description: "查看图片尺寸、格式和文件大小。",
    roles: ["design", "frontend", "operations"],
    category: "design",
    keywords: ["image", "图片", "尺寸", "大小"],
    component: ImageInfoTool,
  },
  {
    id: "contrast",
    title: "对比度检查",
    description: "检查前景色和背景色的 WCAG 对比度。",
    roles: ["design", "frontend", "product"],
    category: "design",
    keywords: ["contrast", "wcag", "可访问性", "颜色", "对比度"],
    component: ContrastTool,
  },
  {
    id: "palette",
    title: "配色板",
    description: "从主色生成可复制配色。",
    roles: ["design", "frontend", "product"],
    category: "design",
    keywords: ["palette", "配色", "主题色", "颜色"],
    component: PaletteTool,
  },
  {
    id: "css-units",
    title: "CSS 单位换算",
    description: "px、rem、vw 与 clamp 片段换算。",
    roles: ["frontend", "design"],
    category: "developer",
    keywords: ["px", "rem", "vw", "clamp", "css"],
    component: UnitTool,
  },
];
